---
title: Yannick Le Maintec, auteur
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: ''
permalink: ":title/"
baseurl: ''
url: ''
site-twitter: 
author: Yannick Le Maintec
author-img: ylm.jpg
author-og-img: ylemaintec-tempolatino.jpg
about-author: Auteur de la rubrique <a href='https://www.lemonde.fr/le-jazz-et-la-salsa/'
  target='_blank'>&#8220;Le&nbsp;jazz&nbsp;et&nbsp;la&nbsp;salsa&#8221;</a> sur<br/>
  le Monde.fr.
social-twitter: salsajazzblog
social-facebook: salsajazzblog
social-email: 
social-instagram: salsajazzblog
analytics: 
markdown: kramdown
plugins:
- jekyll-sitemap
- jekyll-paginate
- jemoji
paginate: 8
paginate_path: "/page/:num"
lang: fr
exclude:
- node_modules
- gulpfile.js
- package.json
- yarn.lock
